# Generated by Django 5.0.4 on 2024-04-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', help_text='O para Open, C para Closed', max_length=1, verbose_name='Status'),
        ),
    ]
